import { Link } from 'react-router-dom';
import {
  BrainCircuit,
  Map,
  FileText,
  FolderKanban,
  MessagesSquare,
  Compass,
  TrendingUp,
  Bot,
  UserPlus,
  ListChecks,
  Sparkles,
  Route,
  Rocket,
  Award,
} from 'lucide-react';
import Navbar from '../../components/layout/Navbar.jsx';
import Footer from '../../components/layout/Footer.jsx';
import './Home.css';

const features = [
  { icon: BrainCircuit, title: 'AI Skill Gap Analysis', text: 'Deep AI analysis of what you know and exactly what you are missing.' },
  { icon: Map, title: 'Personalized Learning Roadmap', text: 'A visual timeline from Beginner to Industry Ready, built for you.' },
  { icon: FileText, title: 'Resume Analysis', text: 'Upload your resume and get ATS score, weak sections, and fixes.' },
  { icon: FolderKanban, title: 'Project Recommendations', text: 'Projects matched to your level with skills, duration, and outcomes.' },
  { icon: MessagesSquare, title: 'Interview Preparation', text: 'Technical, HR, coding challenges and MCQs generated by AI.' },
  { icon: Compass, title: 'Career Guidance', text: 'AI mentor advice on the fastest path to your target role.' },
  { icon: TrendingUp, title: 'Progress Tracking', text: 'Dashboards, charts and scores that grow with every analysis.' },
  { icon: Bot, title: 'AI Mentor', text: 'A career mentor and learning advisor powered by real AI.' },
];

const steps = [
  { icon: UserPlus, title: 'Create Account', text: 'Sign up with your college and department details.' },
  { icon: ListChecks, title: 'Select Your Skills', text: 'Pick a technology and tick the topics you have completed.' },
  { icon: Sparkles, title: 'AI Analyzes Your Gap', text: 'The AI mentor detects missing concepts and weak areas.' },
  { icon: Route, title: 'Get Your Roadmap', text: 'Receive a personalized learning sequence and timeline.' },
  { icon: Rocket, title: 'Build Projects', text: 'Follow recommended projects to strengthen your portfolio.' },
  { icon: Award, title: 'Become Industry Ready', text: 'Prepare for interviews and polish your resume with AI.' },
];

export default function Home() {
  return (
    <div className="page">
      <Navbar />
      <section className="hero container" id="about">
        <span className="badge float">Powered by real AI · Groq + LangChain</span>
        <h1 className="hero-title fade-up">
          Identify Your Skill Gap. <span className="hero-gradient">Build Your Future.</span>
        </h1>
        <p className="hero-subtitle fade-up">
          Use AI to discover missing skills, generate personalized learning roadmaps, analyze
          resumes, prepare for interviews, and become industry-ready.
        </p>
        <div className="hero-actions fade-up">
          <Link to="/register" className="btn btn-primary">Start Skill Analysis</Link>
          <a href="#features" className="btn btn-secondary">Learn More</a>
        </div>
      </section>

      <section className="container" id="features" style={{ paddingTop: 30 }}>
        <h2 className="section-title">Everything you need to get industry-ready</h2>
        <p className="section-subtitle">
          Built for higher secondary students, diploma students, college students, and fresh graduates.
        </p>
        <div className="grid-4">
          {features.map((f) => (
            <div key={f.title} className="glass-card feature-card">
              <span className="feature-icon"><f.icon size={22} /></span>
              <h3>{f.title}</h3>
              <p>{f.text}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="container" style={{ paddingTop: 70 }}>
        <h2 className="section-title">How It Works</h2>
        <p className="section-subtitle">Six simple steps from confusion to a clear career path.</p>
        <div className="grid-3">
          {steps.map((s, i) => (
            <div key={s.title} className="glass-card step-card">
              <span className="step-number">{i + 1}</span>
              <span className="feature-icon"><s.icon size={22} /></span>
              <h3>{s.title}</h3>
              <p>{s.text}</p>
            </div>
          ))}
        </div>
      </section>

      <Footer />
    </div>
  );
}
